language: node_js
node_js:
- 10
services:
- redis-server
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: lLwTsHyaYkxXWW1z4JnpiIurcBo1nBhedMJLlsP39IDzlPdaNSBjNKaWxNUf71t8c9QPmQIKVva7D+oFwJX272qEqaEFKrVFfidorzeq0F/dqryTKfAHuv+QfTTvDKvOja2h63Gh1mdJhp/lh+z9bbuyuJLcXus5blUu30y4avb0/q1LPUq7TIPyiKpl0BJuKYxx4xAIij3Ad/9w+pWvy7WxaAYYXfiRhXYopSqFWzp2+devPBebpNem1B+gUQDLZxI126FJKfdAehBFHX6XeiJY/5ARH4Z+t94h045TEQi/2P9Z20peuzH1aY9m2FHNo0BgT5r8TRe8o9jbTTBHRsg8siwctgqJMXbDVgO8RpQ/fVqvvI3XxiRWTZkjldOrg2SwVKAAWSn8RufJkPx570SCW840+F8ayE6QkSDD6xNMhcDIla3LIIt416+5DTXEzdUANXNmBNo9K9bmhA0za3i8mrOziACfzwNDWECFR2ioTBp5pbJy0acqwblDVijjnjIQF9Jswic/0izQlxDLtxxezXq6JpAeUuVnD38D8u8f9PM2XOd2J+YO/4/4Zu5EzlWwe2N7aoAJe3zPBPL+b1szD0i5C1MSeUZn4AcOKnKFcUHZWw6T0yhy7UrmvYUbiKXQXadunxEkSt24ozhdjcerjgWa1krLUplvAAirbr4=
notifications:
  slack:
    secure: VtATQ/Q1oCrqqdagp5aP+IpSiN6UKI5HCcCQ1Q6H5NXYLYw+E3SltLFShlq2kK0vKUHn5fsCKmt0epATaY68irpol2FKKYsbWvJPuX7koyY0jzoio1UaV3hlPTzZW4+vRuUau799G/4foNtHGqjupSCJUzjI7DCEs+UR4FGbs7DuBCwbHERRp6kXHzUDdVIfCaqXHieTETuvo/DDIqIEUHM04FIV305JpGPqNTBkkXqS+0oF1MeFCetYZdzmWnZWO2aO1kkkJ5V5+09hg+YAio52SGtTMBu467NXSolAh8ehxsgh5A1DEQScAWgZ+XeAtrV6kPz6hdARUGei6Dr7EiJI8nC9tm0ZQBhFRYq7j09TWn6Jp++NXs5AeYWaHRGnaKAGmVfR77Czl2XUX4mzEGYyB8EXZ65zldeG4UvLJjBOnVfHjxDQcOqH+Zw1cbOZ0G70W7kImDdk0H6D6rGHZtfGI1aAn+yjVsCMSkJFsWGCTUrWuT+6iWuMCIv6tkefFTtfyLLgz0PzB+6HRFqRDPpMAYm0jRvTouEg3jsBimz6h+KjQJ0COen7qKd+ePFKDxpXnUHP4cNNQUniaCRWD7H4v8JFrQWeCiChDhsv72BbtP7/etRsgRNC2sbYJTu18k3bMQOCTiK3SZ/f71+jSdEjOt/ZTqG++JxQ4mTQZOU=
