language: node_js
node_js:
- 9
services:
- redis-server
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: lLwTsHyaYkxXWW1z4JnpiIurcBo1nBhedMJLlsP39IDzlPdaNSBjNKaWxNUf71t8c9QPmQIKVva7D+oFwJX272qEqaEFKrVFfidorzeq0F/dqryTKfAHuv+QfTTvDKvOja2h63Gh1mdJhp/lh+z9bbuyuJLcXus5blUu30y4avb0/q1LPUq7TIPyiKpl0BJuKYxx4xAIij3Ad/9w+pWvy7WxaAYYXfiRhXYopSqFWzp2+devPBebpNem1B+gUQDLZxI126FJKfdAehBFHX6XeiJY/5ARH4Z+t94h045TEQi/2P9Z20peuzH1aY9m2FHNo0BgT5r8TRe8o9jbTTBHRsg8siwctgqJMXbDVgO8RpQ/fVqvvI3XxiRWTZkjldOrg2SwVKAAWSn8RufJkPx570SCW840+F8ayE6QkSDD6xNMhcDIla3LIIt416+5DTXEzdUANXNmBNo9K9bmhA0za3i8mrOziACfzwNDWECFR2ioTBp5pbJy0acqwblDVijjnjIQF9Jswic/0izQlxDLtxxezXq6JpAeUuVnD38D8u8f9PM2XOd2J+YO/4/4Zu5EzlWwe2N7aoAJe3zPBPL+b1szD0i5C1MSeUZn4AcOKnKFcUHZWw6T0yhy7UrmvYUbiKXQXadunxEkSt24ozhdjcerjgWa1krLUplvAAirbr4=
