language: node_js
node_js:
- 9
services:
- redis-server
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: TYyZrzlcxgvPOty7gdL6J21NK8jj1Hg23YIKZnvQe2G6uKtUEiik4fyoA0kCnsj+66cPOj1yMeXIVYFulJtWTbYw0X5ZshPxAtiG9y3afwdpw31KqRktYf3IpCpCC7WpLcmlMbqvCFCOQgJmV5KahfbdRILdDHpS2Sjxkav4Ds1AarPtX9FVnU8+kWBy7tbHsgC53HVSYs6/kBW3pCtyI4fzMcckS2q+5RgiEcpjzsg/7S9JSJVKbqqDSQzIxXH/YiKRL1KT3gONCbRpJLkaFbjLhSN9jy6WKGHdD9GzonVTO47ci3r6OujC24xn9VNN9bZIEpd4xNfp+xqeqiViwPl+1eKMNRFmbrBw4vdOYGXBePPo0JzewLwY44hnBCsmceNl/rjk8huk9krkLng60wNGhEeZj2rxiuAlT6vHx05bajYdnmXhKJt1JKBCVXwOD4aUd6jYg00trrgygcaR9R20DQWfRILxExriq454JodwTKuExbJZtRG6R2EDm2AmFXDUH70PIcosq7Js2iFz+QERV0sBS5sjAf5d8O/r9o9DLSePcjRc9at8sJ3Hnu6KrnuixCZYKG03ZogNJSPOexwTNqTQt6GN2chwENFh/C+dUjnfjbFyf5f0hb4QMUh60F2PaGINsVT9PAWAGuxVokfSI1vxruzEtUT/RrijH8c=
