language: node_js
node_js:
- 10
services:
- redis-server
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: P0kyelP4GBby2QYsHJB3p3oCkE0io3qunYZo6DlmjzLuqlBxsSNZSHXhzrl2D7zx8Cmq9LIuWaz+OgKF4A2RX2ZBKbQNaP7uGfYv5FCHS9WOxcD1UVP6Qm9xW5sHfPY7ER50GUPVRsYYeeeNV6FF+5522zeHEev7EramUMLa4AVeT6G1J68kJXcEFuyB3H1XTWmpu9K5bYgGWAglqelbS0O41FGzN7GkEFodLAdai6PNeC3zq6AkIfk+duHhrCSyGyKTvJNo25xNxyVPSv86rrKLCrdMim5OsIG2AZDcrYFcW9R129N7MUAglfFfa8FRK2/XeybasBhxDkcfN7QQ08qi00/6XPzqk7eS0qI6ZNQz2taWOptLw+9utfFutD2VRvhiLPk9PkprPRQqj4KQsBUmrVYCylu5T4Gjc2/bE+8STr2rsTMgFh6l8jG6ydnWnlV51/QehHnaV2RrF3TlcEh2Gc9e4cDXoxJdjW/gKhF9qyxr56Y5VckP5GCKh7g1ZUcc55Pbu2peRJFggcAgwhtGsybDyS928OSLXhenJHqkv4ZXNM1nec/XwQAvbNZMIrvxg9s8hGgUg9Ja9NXl7flOdxOx0obOx3JrlF1eypr0VM356qU0lW9stG7TvipSj2XXjcnG+EfvLLu53x6M4mkpTWNSNDlYTQ9INgrbYgw=
notifications:
  slack:
    secure: Xle16cyKZ2lf1OtMYOiVkIqTbT+5kdF7yvHzcBLkSXPe2BS0sf3iuHyF5vF0XsFMsph3PpVUU+g18OUaF/ahI0HqOHLf6/l53GHLUyLMWzYpvq334YIiGiRYjLsUByb0o26AfKcYZ//TcTfNJ/EukQGZMO5YtfF5W6H6aTa0tGU/bNjfI9qEd04FCzhTNa4Xbib8OLUJZSLnEnIZcgv+YiRCC7gWllL/mNrVVqj23DJOhlV1azeZEJ4z296FPV+mzQFSj8O3H05zv3uEpYm3H8H7Dq9Zu3FJzs01OADc1v1W4943mmRfNlclMPQLgYT3xJcyMDR73ZmeCFZWeg/0c3qZdEKK8ebxEevJ7T3kOSQ3h6mmVpCULA0dA0O49F2SVqrYbxbqBoXt+X5LkkVGdaozBG6HJiqGi8BvIgsHnj5YMsr47kLlDX2Y/e9skTnzl7ajJO3SI+eR3DmtQzhq33m86M9ZsxegGk9fsBg9qqQYSDFY/Tu531B5uce3SWI7iPsOSKDuuxIdHjJKS94QruoCu89mZAxcIi9vZLX7oVJz51R8g5Caacn27Lkp5RPgHz/hKIq/unx7OyZOzXPagVMw14SopNBfkD2jE1zTw0LrnkCKsLuOmyR4blKqxc23fPjFquVNU9rOFcsZYC/dkuQc2cd/ov8A2YE85bTEZks=
deploy:
- provider: npm
  api_key:
    secure: mniIbO4j6w9wTCDrbic2tI6KImh9Rd9b7HKedKfc2LYUMV5QE+BUy+5xGhxcwmSZfonYT8722Xwvq7CeYEmrV6FVN02l8DG/Jb+SMLQznuPo1K5Q0+glYrtphJaKdznWgD6T+K/dajaxlM+eXCxlGuI0NmDnrd3/CB2mOEbeTIRrXBnM68Y+q1Vhkag5fzKXLwPRbK6yrk0PZFiSZASswno+x1q1YReIyqR3wrFQDBRq5twpPYTyKdH+b+Pfhavnv0jILPAGjB4/e19nQjFLo9NvtF+BGN9aYSLJlRTlk4hFGltX2u0Uu08QqGz5z6GfAbM91ODe4bXxpMkeESJYxfp3kqJssJUgMtH9zAOekIdK6XDl1EqsHCeA186eSqLVMTU6YVELyxsxosWDrkWJEWt+wL4ydA16rT38OpzijEjiCJBZjTj8TPd1paHdReOsInMjo/WW+YGmFWtz+7NgzNawaooANpJf7slhpXZpMg4jJXgFNilaYvjFMJ0FNL4aoN6xyorNcYhQfKQ1wng2RToGiwCpcZITrdcZV8uEGo6njuY52zlTGXUvVhr9OwjX/EVzbhYLhUOzqhHEeYatgf/Wt+CQ7a+FfRms7Psj2pAtAp9XFqk4pTJWel8fiXS2tj87ssHKUESKufk2L3F3XJUbBEXQSZbxr0LOplCQUqI=
  email:
    secure: EDjFtPFWAszAh3hNOrTBdEWoPhBaDXVODPBnE18si3/mjI33PNxa4RBnbhX5fZnIT3whEv680qF6C50OWNW4pL4UjRKKG3hAdgRlVQo/dxR+DDZbBnBhdApa+vjvBu4zcfFKfZ9eiipkdDx7f8NNyDNxn6eBNJxj5Q7Vx2gAbf19RTXFTSwY8qsXNy5d6Nep+PJN0UI3HV2X0HwKG7+Krb8wOa5JArUaRazrrz7grO5TnHuYC3GUQ6+shImNJRUeTwRTu2ogGN0tQwTTjHa3NoIo4LlA3u7oRe/CWSUK4ynGYcxGq0sBQtEjcfEu3hbYyDb6jUQLRX9F/J19E4dwuQRwjbPgVbHAxF6HWhH2K1O9BNzOEKaZrSeJdzrrT4XCIQiAJqIy8uo5YnpsyhrQA/MsBNhreo8flPO7kbiqqfj2gpwWwaf1pZMEU62rYilLU1NHJD5qq/RKYpGxbdNkrJWTeFmi2RGLzDLXKyMfcjHZfG+/eopf1c5+sdDGA+43MPnPDPfeCxgIuXAjTo6k1f2HBsML+tZgkNcceaTZM1ZAnKvMmDQkGvh1oeEXxiRqHD7tSfC3gSN58nqswLB34deDYeZhtXZjlMaxVI1HTGeBbQDCOnBbKNFm09jywbWAYgtgTKMX5JLUG8+C2OzEtCTsGE081xptBc2MPbpuq+0=
